name: RunRepeat Scraper

on:
  schedule:
    - cron: "0 2 * * 5" # Every Friday at 2 AM UTC
  workflow_dispatch: # manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper
        run: node scraper.js

      - name: Commit & Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B update-runrepeat-shoes
          git add runrepeat-shoes.json
          git commit -m "Weekly update: runrepeat shoes" || echo "No changes to commit"
          git push origin update-runrepeat-shoes --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Changes
        id: changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Create Pull Request
        if: steps.changes.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-runrepeat-shoes
          title: "Weekly update: runrepeat shoes"
          body: "This pull request contains the weekly update for runrepeat shoes."
